# Generated by Django 4.0.6 on 2023-04-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=4)),
                ('mobile', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('previous_balance', models.IntegerField(max_length=250)),
                ('status', models.CharField(choices=[('Active', 'active'), ('In Active', 'in_active')], default='no_active', max_length=250)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeapp.office')),
            ],
        ),
    ]
