# Generated by Django 4.0.6 on 2023-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='previous_balance',
            field=models.IntegerField(),
        ),
    ]
