# Generated by Django 4.0.6 on 2023-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('Active', 'active'), ('In Active', 'in_active')], default='no_active', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('Active', 'active'), ('In Active', 'in_active')], default='no_active', max_length=250)),
            ],
        ),
    ]
