# Generated by Django 4.0.6 on 2023-04-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Active', 'active'), ('In Active', 'in_active')], default='no_active', max_length=250)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usertype')),
            ],
        ),
    ]
